# First Line of the code

In [1]:
# Library
import pandas as pd
import numpy as np

# # Google Colab
# from google.colab import files

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns
import missingno
from IPython.display import display

# EDA Libraries
from skrub import TableReport

# Feature Engineering
from sklearn.base import clone
from feature_engine.encoding import RareLabelEncoder
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import RobustScaler
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, OrdinalEncoder
from sklearn.compose import ColumnTransformer
import category_encoders as ce

# Model Selection
from sklearn.dummy import DummyClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV,StratifiedKFold,train_test_split, cross_val_score, cross_validate
from sklearn.metrics import classification_report, confusion_matrix, average_precision_score, make_scorer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from xgboost import XGBClassifier
import lightgbm as lgb
from sklearn.metrics import f1_score, accuracy_score, recall_score, precision_score
from sklearn.metrics import roc_curve, roc_auc_score

# Imbalance Library
from imblearn.over_sampling import SMOTE, RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler, NearMiss
from imblearn.combine import SMOTEENN
from imblearn.pipeline import Pipeline as ImbPipeline


# Ignore Warning
import sys
import warnings
if not sys.warnoptions:
    warnings.simplefilter("ignore")

# Set max columns
pd.set_option('display.max_columns', None)

In [2]:
# uploaded = files.upload()
path = "data.csv"
df_model = pd.read_csv(path)

In [3]:
# hapus kolom stay_duration dan total_guest
df_model.drop(columns=['stay_duration', 'total_guests'], inplace=True)

In [4]:
# General table report
report = TableReport(df_model, max_plot_columns=32, max_association_columns=32)
report

Processing column  27 / 27

In [5]:
listItem = []
for col in df_model.columns :
    listItem.append([col, df_model[col].dtype, df_model[col].isna().sum(), round((df_model[col].isna().sum()/len(df_model[col])) * 100,2),
                    df_model[col].nunique(), list(df_model[col].drop_duplicates().sample(2).values)])

df_modelDesc = pd.DataFrame(columns=['dataFeatures', 'dataType', 'null', 'nullPct', 'unique', 'uniqueSample'],
                     data=listItem)
df_modelDesc

,dataFeatures,dataType,null,nullPct,unique,uniqueSample
0,hotel,object,0,0.0,2,"[City Hotel, Resort Hotel]"
1,is_canceled,int64,0,0.0,2,"[1, 0]"
2,lead_time,int64,0,0.0,479,"[450, 128]"
3,arrival_date_year,int64,0,0.0,3,"[2017, 2016]"
4,arrival_date_month,object,0,0.0,12,"[June, November]"
5,arrival_date_day_of_month,int64,0,0.0,31,"[5, 1]"
6,stays_in_weekend_nights,int64,0,0.0,17,"[5, 14]"
7,stays_in_week_nights,int64,0,0.0,33,"[14, 0]"
8,adults,int64,0,0.0,14,"[55, 27]"
9,children,int64,0,0.0,5,"[3, 1]"
10,babies,int64,0,0.0,5,"[0, 1]"
11,meal,object,0,0.0,5,"[FB, HB]"
12,country,object,0,0.0,178,"[ISR, LCA]"
13,market_segment,object,0,0.0,8,"[Complementary, Direct]"
14,distribution_channel,object,0,0.0,5,"[GDS, Undefined]"
15,is_repeated_guest,int64,0,0.0,2,"[0, 1]"
16,previous_cancellations,int64,0,0.0,15,"[26, 6]"
17,previous_bookings_not_canceled,int64,0,0.0,73,"[67, 16]"
18,reserved_room_type,object,0,0.0,9,"[F, B]"
19,assigned_room_type,object,0,0.0,11,"[G, F]"
20,booking_changes,int64,0,0.0,19,"[5, 17]"
21,deposit_type,object,0,0.0,3,"[Non Refund, Refundable]"
22,days_in_waiting_list,int64,0,0.0,127,"[39, 98]"
23,customer_type,object,0,0.0,4,"[Transient, Group]"
24,adr,float64,0,0.0,8864,"[103.77, 86.46]"
25,required_car_parking_spaces,int64,0,0.0,5,"[3, 1]"
26,total_of_special_requests,int64,0,0.0,6,"[0, 1]"

# Section 6: Data Preparation And Feature Engineering

## 6.1 Initialization

In [6]:
df_model.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests
0,Resort Hotel,0,342,2015,July,1,0,0,2,0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,0,Transient,0.0,0,0
1,Resort Hotel,0,737,2015,July,1,0,0,2,0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,0,Transient,0.0,0,0
2,Resort Hotel,0,7,2015,July,1,0,1,1,0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,0,Transient,75.0,0,0
3,Resort Hotel,0,13,2015,July,1,0,1,1,0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,0,Transient,75.0,0,0
4,Resort Hotel,0,14,2015,July,1,0,2,2,0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,0,Transient,98.0,0,1

In [7]:
df_model.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87228 entries, 0 to 87227
Data columns (total 27 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           87228 non-null  object
 1   is_canceled                     87228 non-null  int64
 2   lead_time                       87228 non-null  int64
 3   arrival_date_year               87228 non-null  int64
 4   arrival_date_month              87228 non-null  object
 5   arrival_date_day_of_month       87228 non-null  int64
 6   stays_in_weekend_nights         87228 non-null  int64
 7   stays_in_week_nights            87228 non-null  int64
 8   adults                          87228 non-null  int64
 9   children                        87228 non-null  int64
 10  babies                          87228 non-null  int64
 11  meal                            87228 non-null  object
 12  country                         87228 non-null  object
 13  market_segment                  87228 non-null  object
 14  distribution_channel            87228 non-null  object
 15  is_repeated_guest               87228 non-null  int64
 16  previous_cancellations          87228 non-null  int64
 17  previous_bookings_not_canceled  87228 non-null  int64
 18  reserved_room_type              87228 non-null  object
 19  assigned_room_type              87228 non-null  object
 20  booking_changes                 87228 non-null  int64
 21  deposit_type                    87228 non-null  object
 22  days_in_waiting_list            87228 non-null  int64
 23  customer_type                   87228 non-null  object
 24  adr                             87228 non-null  float64
 25  required_car_parking_spaces     87228 non-null  int64
 26  total_of_special_requests       87228 non-null  int64
dtypes: float64(1), int64(16), object(10)
memory usage: 18.0+ MB

In [8]:
# Cast each columns to its according data type
df_model['hotel'] = df_model['hotel'].astype("category")
df_model['is_canceled'] = df_model['is_canceled'].astype("category")
df_model['arrival_date_year'] = df_model['arrival_date_year'].astype("category")
df_model['arrival_date_month'] = df_model['arrival_date_month'].astype("category")
df_model['arrival_date_day_of_month'] = df_model['arrival_date_day_of_month'].astype("category")
df_model['children'] = df_model['children'].astype(int)
df_model['meal'] = df_model['meal'].astype("category")
df_model['country'] = df_model['country'].astype("category")
df_model['market_segment'] = df_model['market_segment'].astype("category")
df_model['distribution_channel'] = df_model['distribution_channel'].astype("category")
df_model['is_repeated_guest'] = df_model['is_repeated_guest'].astype("category")
df_model['reserved_room_type'] = df_model['reserved_room_type'].astype("category")
df_model['assigned_room_type'] = df_model['assigned_room_type'].astype("category")
df_model['deposit_type'] = df_model['deposit_type'].astype("category")
df_model['customer_type'] = df_model['customer_type'].astype("category")

In [9]:
# Create seen & unseen dataframes

data_seen, data_unseen = train_test_split(df_model, test_size=0.2,
                                          random_state=42,
                                          stratify=df_model["is_canceled"]) # stratify digunakan untuk menjaga proporsi target antara data seen dan data unseen
                                                                    # stratify khusus classification

# data_seen.to_csv("data_train.csv", index=False)
# data_unseen.to_csv("data_test.csv", index=False)

In [10]:
print("data unseen size:", data_unseen.shape)
print("data seen size:", data_seen.shape)

data unseen size: (17446, 27)
data seen size: (69782, 27)

### 6.1.1 Define Feature and Target

In [11]:
# Checking Unique Data Type
categorical_cols = df_model.select_dtypes(include='category').columns.tolist()
numerical_cols = df_model.select_dtypes(include='int64').columns.tolist()

print("Fitur kategorikal:", categorical_cols)
print("Fitur numerik:", numerical_cols)

Fitur kategorikal: ['hotel', 'is_canceled', 'arrival_date_year', 'arrival_date_month', 'arrival_date_day_of_month', 'meal', 'country', 'market_segment', 'distribution_channel', 'is_repeated_guest', 'reserved_room_type', 'assigned_room_type', 'deposit_type', 'customer_type']
Fitur numerik: ['lead_time', 'stays_in_weekend_nights', 'stays_in_week_nights', 'adults', 'children', 'babies', 'previous_cancellations', 'previous_bookings_not_canceled', 'booking_changes', 'days_in_waiting_list', 'required_car_parking_spaces', 'total_of_special_requests']

In [12]:
x = data_seen.drop(columns=['is_canceled'])
y = data_seen['is_canceled']

In [13]:
# Creating training and test sets
x_train,x_test,y_train,y_test=train_test_split(x,y,stratify=y,test_size=0.2,random_state=2021)

### 6.1.2 Create Custome Transformer

Now let’s perform feature encoding for the categorical features in our dataset.  
Here is the plan:

1. Transform the column `arrival_date_month` using **Ordinal Encoding**, since months have a clear natural order from January to December.

2. Transform the columns `hotel`, `meal`, `market_segment`, `distribution_channel`, `reserved_room_type`, `assigned_room_type`, `deposit_type`, and `customer_type` using **One Hot Encoding**, because they are categorical nominal features (no natural order) with a relatively small number of unique values.

3. Transform the column `country` using **Binary Encoding**, because it contains a very large number of unique values (150+ countries). Using One Hot Encoding would create too many new columns, while Binary Encoding keeps the dimensionality low but still preserves information.

4. For the column `deposit_type`, we also apply **One Hot Encoding**, since it only contains three categories (`No Deposit`, `Non Refund`, `Refundable`) and does not have a natural order.

> Note: We need to be cautious, as some encoding techniques may increase the number of features significantly. The above strategy balances interpretability and computational efficiency.

In [14]:
class ColumnCombiner(BaseEstimator, TransformerMixin):
    """
    Combine multiple numeric columns into a single new column.
    Example: adults + children + babies -> total_guests
    """
    def __init__(self, columns=None, new_column_name=None):
        self.columns = columns or []
        self.new_column_name = new_column_name
    
    def fit(self, X, y=None):
        return self
    
    def transform(self, X):
        X = X.copy()
        if all(col in X.columns for col in self.columns):
            X[self.new_column_name] = X[self.columns].fillna(0).sum(axis=1)
            X.drop(self.columns, axis=1, inplace=True, errors="ignore")
        return X
    
    def get_feature_names_out(self):
        return [self.new_column_name]
    
class ColumnDropper(BaseEstimator, TransformerMixin):
    """
    Drop specified columns if they exist in the DataFrame.
    """
    def __init__(self, columns=None):
        self.columns = columns or []
    
    def fit(self, X, y=None):
        return self
    
    def transform(self, X):
        X = X.copy()
        return X.drop(columns=[c for c in self.columns if c in X.columns], errors="ignore")
    
class MultiColumnCombiner(BaseEstimator, TransformerMixin):
    """
    Combine multiple sets of columns into new features at once.
    Example:
    combiner = MultiColumnCombiner(
        combinations={
            "total_guests": ["adults", "children", "babies"],
            "total_stay_nights": ["stays_in_weekend_nights", "stays_in_week_nights"]
        }
    )
    """
    def __init__(self, combinations=None):
        self.combinations = combinations or {}
    
    def fit(self, X, y=None):
        return self
    
    def transform(self, X):
        X = X.copy()
        for new_col, cols in self.combinations.items():
            if all(c in X.columns for c in cols):
                X[new_col] = X[cols].fillna(0).sum(axis=1)
                X.drop(cols, axis=1, inplace=True, errors="ignore")
        return X
    
    def get_feature_names_out(self):
        return list(self.combinations.keys())

class OutlierClipper(BaseEstimator, TransformerMixin):
    def __init__(self, columns, whisker=1.5):
        self.columns = columns
        self.whisker = whisker
        self.bounds_ = {}

    def fit(self, X, y=None):
        X = X.copy()
        for col in self.columns:
            if col in X.columns:
                s = pd.to_numeric(X[col], errors="coerce").dropna()
                if len(s) > 0:
                    q1, q3 = s.quantile(0.25), s.quantile(0.75)
                    iqr = q3 - q1
                    self.bounds_[col] = (q1 - self.whisker*iqr, q3 + self.whisker*iqr)
        return self

    def transform(self, X):
        X = X.copy()
        for col, (lb, ub) in self.bounds_.items():
            X[col] = pd.to_numeric(X[col], errors="coerce")
            X[col] = X[col].clip(lower=lb, upper=ub).fillna(X[col].median())
        return X

    def get_feature_names_out(self, input_features=None):
        return input_features if input_features is not None else self.columns

class ADRScaler(BaseEstimator, TransformerMixin):
    """Scale adr column using RobustScaler"""
    def __init__(self, column="adr"):
        self.column = column
        self.scaler = RobustScaler()
        self.fitted_ = False
    
    def fit(self, X, y=None):
        if self.column in X.columns:
            self.scaler.fit(X[[self.column]])
            self.fitted_ = True
        return self
    
    def transform(self, X):
        X = X.copy()
        if self.fitted_ and self.column in X.columns:
            X[self.column] = self.scaler.transform(X[[self.column]])
        return X
    
    def get_feature_names_out(self, input_features=None):
        return input_features if input_features is not None else self.columns

class RareLabelEncoder(BaseEstimator, TransformerMixin):
    def __init__(self, tol=0.01, n_categories=1, replace_with="Other"):
        self.tol = tol
        self.n_categories = n_categories
        self.replace_with = replace_with

    def fit(self, X, y=None):
        # pastikan DataFrame
        if isinstance(X, np.ndarray):
            X = pd.DataFrame(X)

        self.columns_ = X.columns
        self.rare_categories_ = {}
        for col in X.columns:
            freqs = X[col].value_counts(normalize=True)
            rare_cats = freqs[freqs < self.tol].index
            if len(freqs) - len(rare_cats) < self.n_categories:
                rare_cats = freqs.sort_values().index[self.n_categories:]
            self.rare_categories_[col] = set(rare_cats)
        return self

    def transform(self, X):
        # pastikan DataFrame
        array_input = False
        if isinstance(X, np.ndarray):
            X = pd.DataFrame(X, columns=self.columns_)
            array_input = True

        X_copy = X.copy()
        for col, rare_cats in self.rare_categories_.items():
            X_copy[col] = X_copy[col].where(~X_copy[col].isin(rare_cats), self.replace_with)

        return X_copy.values if array_input else X_copy

    def get_feature_names_out(self, input_features=None):
        return input_features if input_features is not None else self.columns_

In [15]:
feature_generator = MultiColumnCombiner(
        combinations={
            "total_guests": ["adults", "children", "babies"],
            "total_stay_nights": ["stays_in_weekend_nights", "stays_in_week_nights"]
        }
    )
feature_dropper = ColumnDropper(columns=['arrival_date_week_number', 'agent', 'company', 'reservation_status', 'reservation_status_date'])

display(feature_generator.fit_transform(x_train).head(1))
display(feature_dropper.fit_transform(x_train).head(1))

,hotel,lead_time,arrival_date_year,arrival_date_month,arrival_date_day_of_month,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,total_guests,total_stay_nights
645,Resort Hotel,33,2015,July,25,HB,PRT,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,0,Transient,142.03,0,1,4,5

,hotel,lead_time,arrival_date_year,arrival_date_month,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests
645,Resort Hotel,33,2015,July,25,2,3,2,2,0,HB,PRT,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,0,Transient,142.03,0,1

In [16]:
# Define month ordering for OrdinalEncoder
month_order = [['January','February','March','April','May','June',
                'July','August','September','October','November','December']]

## 6.2 Feature Engineering Setup

In [17]:
# =============================
#  Numerical Features Pipeline
# =============================
num_pipeline = Pipeline([
    ("clipper", OutlierClipper(columns=["adr"], whisker=3.0)),  # handle outliers
    ("scaler", ADRScaler())  # robust scaling on ADR
])

# ==================================
#  Categorical Features Pipeline (OHE)
# ==================================
ohe_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore", drop="first"))
])

# ==================================
#  Categorical Features Pipeline (Binary)
# ==================================
binary_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", ce.BinaryEncoder())
])

# ==================================
#  Categorical Features Pipeline (Ordinal)
# ==================================
ordinal_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OrdinalEncoder(categories=month_order))   # dari sklearn.preprocessing
])

display(num_pipeline, ohe_pipeline, binary_pipeline, ordinal_pipeline)

Pipeline(steps=[('clipper', OutlierClipper(columns=['adr'], whisker=3.0)),
                ('scaler', ADRScaler())])

Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('encoder',
                 OneHotEncoder(drop='first', handle_unknown='ignore'))])

Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('encoder', BinaryEncoder())])

Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('encoder',
                 OrdinalEncoder(categories=[['January', 'February', 'March',
                                             'April', 'May', 'June', 'July',
                                             'August', 'September', 'October',
                                             'November', 'December']]))])

In [18]:
# Rare Label OHE Pipeline
rare_ohe_pipeline = clone(ohe_pipeline)
rare_ohe_pipeline.steps.insert(1, ("rare_encoder", RareLabelEncoder(tol=0.01, n_categories=1, replace_with="Other")))

# Rare Label Binary Pipeline
rare_binary_pipeline = clone(binary_pipeline)
rare_binary_pipeline.steps.insert(1, ("rare_encoder", RareLabelEncoder(tol=0.01, n_categories=1, replace_with="Other")))

# Rare Label Ordinal Pipeline (opsional, kalau ada kategori ordinal yang terlalu banyak)
rare_ordinal_pipeline = clone(ordinal_pipeline)
rare_ordinal_pipeline.steps.insert(1, ("rare_encoder", RareLabelEncoder(tol=0.01, n_categories=1, replace_with="Other")))

display(rare_ohe_pipeline, rare_binary_pipeline, rare_ordinal_pipeline)

Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('rare_encoder', RareLabelEncoder()),
                ('encoder',
                 OneHotEncoder(drop='first', handle_unknown='ignore'))])

Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('rare_encoder', RareLabelEncoder()),
                ('encoder', BinaryEncoder())])

Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('rare_encoder', RareLabelEncoder()),
                ('encoder',
                 OrdinalEncoder(categories=[['January', 'February', 'March',
                                             'April', 'May', 'June', 'July',
                                             'August', 'September', 'October',
                                             'November', 'December']]))])

In [19]:
num_features = [
    "lead_time", 
    "arrival_date_day_of_month",
    "total_stay_nights",         # hasil combine stays
    "total_guests",              # hasil combine guests
    "previous_cancellations", 
    "previous_bookings_not_canceled", 
    "booking_changes", 
    "days_in_waiting_list", 
    "adr", 
    "required_car_parking_spaces", 
    "total_of_special_requests"
]

ohe_features = [
    "hotel", 
    "meal", 
    "market_segment", 
    "distribution_channel", 
    "reserved_room_type", 
    "assigned_room_type", 
    "deposit_type", 
    "customer_type"
]

binary_features = [
    "country"
]

ordinal_features = [
    "arrival_date_month"
]

In [20]:
# Baseline Preprocessor
baseline_preprocessor = ColumnTransformer([
    ("num_pipeline", num_pipeline, num_features),
    ("ohe_pipeline", ohe_pipeline, ohe_features),
    ("binary_pipeline", binary_pipeline, binary_features)
], remainder="drop", verbose_feature_names_out=False)

# Baseline Preprocessor + Rare Label Encoding
rare_preprocessor = ColumnTransformer([
    ("num_pipeline", num_pipeline, num_features),
    ("ohe_pipeline", rare_ohe_pipeline, ohe_features),
    ("binary_pipeline", rare_binary_pipeline, binary_features)
], remainder="drop", verbose_feature_names_out=False)

In [21]:
display(baseline_preprocessor, rare_preprocessor)

ColumnTransformer(transformers=[('num_pipeline',
                                 Pipeline(steps=[('clipper',
                                                  OutlierClipper(columns=['adr'],
                                                                 whisker=3.0)),
                                                 ('scaler', ADRScaler())]),
                                 ['lead_time', 'arrival_date_day_of_month',
                                  'total_stay_nights', 'total_guests',
                                  'previous_cancellations',
                                  'previous_bookings_not_canceled',
                                  'booking_changes', 'days_in_waiting_list',
                                  'adr', 'required_car_parking_sp...
                                                 ('encoder',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore'))]),
                                 ['hotel', 'meal', 'market_segment',
                                  'distribution_channel', 'reserved_room_type',
                                  'assigned_room_type', 'deposit_type',
                                  'customer_type']),
                                ('binary_pipeline',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder', BinaryEncoder())]),
                                 ['country'])],
                  verbose_feature_names_out=False)

ColumnTransformer(transformers=[('num_pipeline',
                                 Pipeline(steps=[('clipper',
                                                  OutlierClipper(columns=['adr'],
                                                                 whisker=3.0)),
                                                 ('scaler', ADRScaler())]),
                                 ['lead_time', 'arrival_date_day_of_month',
                                  'total_stay_nights', 'total_guests',
                                  'previous_cancellations',
                                  'previous_bookings_not_canceled',
                                  'booking_changes', 'days_in_waiting_list',
                                  'adr', 'required_car_parking_sp...
                                                                handle_unknown='ignore'))]),
                                 ['hotel', 'meal', 'market_segment',
                                  'distribution_channel', 'reserved_room_type',
                                  'assigned_room_type', 'deposit_type',
                                  'customer_type']),
                                ('binary_pipeline',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('rare_encoder',
                                                  RareLabelEncoder()),
                                                 ('encoder', BinaryEncoder())]),
                                 ['country'])],
                  verbose_feature_names_out=False)

In [22]:
# # Define transformers
# transformer = ColumnTransformer([
#     # One Hot Encoding for nominal small-cardinality features
#     ('onehot', OneHotEncoder(drop='first', handle_unknown='ignore'), 
#      ['hotel', 'meal', 'market_segment', 'distribution_channel',
#       'reserved_room_type', 'assigned_room_type', 'deposit_type', 'customer_type']),
    
#     # Ordinal Encoding for months
#     ('ordinal', OrdinalEncoder(categories=month_order), ['arrival_date_month']),
    
#     # Binary Encoding for high-cardinality 'country'
#     ('binary', ce.BinaryEncoder(), ['country'])
    
# ], remainder='passthrough')

## 6.3 Feature Engineering Overview

In [23]:
x_train_pre = feature_generator.fit_transform(x_train)
x_train_pre = baseline_preprocessor.fit_transform(x_train_pre)
fe_overview = pd.DataFrame(x_train_pre, columns=baseline_preprocessor.get_feature_names_out())

In [24]:
print("Before Preprocessing:")
display(x_train.head(1))

print("After Preprocessing:")
display(fe_overview.head(1))

Before Preprocessing:

,hotel,lead_time,arrival_date_year,arrival_date_month,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests
645,Resort Hotel,33,2015,July,25,2,3,2,2,0,HB,PRT,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,0,Transient,142.03,0,1

After Preprocessing:

,lead_time,arrival_date_day_of_month,total_stay_nights,total_guests,previous_cancellations,previous_bookings_not_canceled,booking_changes,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,hotel_Resort Hotel,meal_FB,meal_HB,meal_SC,meal_Undefined,market_segment_Complementary,market_segment_Corporate,market_segment_Direct,market_segment_Groups,market_segment_Offline TA/TO,market_segment_Online TA,market_segment_Undefined,distribution_channel_Direct,distribution_channel_GDS,distribution_channel_TA/TO,distribution_channel_Undefined,reserved_room_type_B,reserved_room_type_C,reserved_room_type_D,reserved_room_type_E,reserved_room_type_F,reserved_room_type_G,reserved_room_type_H,reserved_room_type_L,assigned_room_type_B,assigned_room_type_C,assigned_room_type_D,assigned_room_type_E,assigned_room_type_F,assigned_room_type_G,assigned_room_type_H,assigned_room_type_I,assigned_room_type_K,deposit_type_Non Refund,deposit_type_Refundable,customer_type_Group,customer_type_Transient,customer_type_Transient-Party,0_0,0_1,0_2,0_3,0_4,0_5,0_6,0_7
0,33.0,25.0,5.0,4.0,0.0,0.0,0.0,0.0,0.699275,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [25]:
x_train_pre = feature_generator.fit_transform(x_train)
x_train_pre = rare_preprocessor.fit_transform(x_train_pre)
fe_overview = pd.DataFrame(x_train_pre, columns=rare_preprocessor.get_feature_names_out())

In [26]:
# testing = pd.DataFrame(transformer.fit_transform(x_train),columns=transformer.get_feature_names_out())
# testing.head()

# Section 7: Model Development

In [26]:
# Individual Models (Baseline)
models = {
    "Baseline Model": DummyClassifier(),
    "K-Nearest Neighbors": KNeighborsClassifier(),
    "Decision Tree Classifier": DecisionTreeClassifier(random_state=42),
    "Logistic Regression": LogisticRegression(random_state=42),
    "Random Forest Classifiers": RandomForestClassifier(random_state=42),
    "Adaboost Classifier": AdaBoostClassifier(random_state=42),
    "XGBoost Classifier": XGBClassifier(random_state=42)
}

In [ ]:
# # import numpy as np
# # from sklearn.metrics import confusion_matrix, make_scorer

# # def business_impact_score(y_true, y_pred, 
# #                                 cost_fn=450, cost_fp=200, value_tp=450,
# #                                 adr=None, stay_nights=None):
# #     """
# #     Custom business impact metric for hotel booking cancellations.
    
# #     Parameters:
# #     - y_true: True labels (0 = Not Canceled, 1 = Canceled)
# #     - y_pred: Predicted labels (0 or 1)
# #     - cost_fn: Cost of missing a cancellation (False Negative)
# #     - cost_fp: Cost of wrongly flagging a valid booking as canceled (False Positive)
# #     - value_tp: Value saved per correctly detected cancellation (True Positive)
# #     - adr: Optional array of ADR (Average Daily Rate) for scaling by actual booking value
# #     - stay_nights: Optional array of total stay nights for scaling
    
# #     Returns:
# #     - net_impact: Net business impact (the higher, the better)
# #     """
    
# #     tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    
# #     if adr is not None and stay_nights is not None:
# #         # Calculate actual revenue impact per booking
# #         tp_value = np.sum([a*s for yt, yp, a, s in zip(y_true, y_pred, adr, stay_nights) if yt==1 and yp==1])
# #         fn_loss  = np.sum([a*s for yt, yp, a, s in zip(y_true, y_pred, adr, stay_nights) if yt==1 and yp==0])
# #     else:
# #         tp_value = tp * value_tp
# #         fn_loss  = fn * cost_fn
    
# #     fp_loss = fp * cost_fp
    
# #     net_impact = tp_value - fn_loss - fp_loss
# #     return net_impact

# # # Make scorer for sklearn (higher is better)
# # hotel_business_scorer = make_scorer(business_impact_score, greater_is_better=True)

# # Initialize the metrics

# main_metrics = "average_precision_score" # PR-AUC
# business_scorer = make_scorer(
#     business_impact_score,
#     greater_is_better=True,  # karena kita ingin nilai impact makin besar
# )

In [27]:
def business_impact_score(y_true, y_pred, adr, stay_nights, 
                          cost_fp=200):
    """
    Business impact score for hotel bookings, scaled by actual booking value.
    
    Parameters:
    - y_true: True labels (0 = Not Canceled, 1 = Canceled)
    - y_pred: Predicted labels (0 or 1)
    - adr: Array-like, Average Daily Rate per booking
    - stay_nights: Array-like, total nights stayed per booking
    - cost_fp: Cost of wrongly flagging a valid booking as canceled
    
    Returns:
    - net_impact: Net business impact (higher is better)
    """
    
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    
    # Calculate actual monetary value of bookings
    booking_values = np.array(adr) * np.array(stay_nights)
    
    # Revenue saved: correctly predicted cancellations
    tp_value = np.sum([val for yt, yp, val in zip(y_true, y_pred, booking_values) if yt==1 and yp==1])
    
    # Revenue lost: missed cancellations (FN)
    fn_loss  = np.sum([val for yt, yp, val in zip(y_true, y_pred, booking_values) if yt==1 and yp==0])
    
    # Reputation / opportunity loss: FP × fixed cost
    fp_loss  = fp * cost_fp
    
    net_impact = tp_value - fn_loss - fp_loss
    return net_impact

# Initialize metrics
main_metrics = "average_precision_score"  # PR-AUC
business_scorer = make_scorer(
    business_impact_score,
    greater_is_better=True
)

In [28]:
# Example data
y_true = [0, 1, 1, 0]
y_pred = [0, 0, 1, 1]
adr = [100, 120, 80, 90]            # ADR per booking
stay_nights = [2, 3, 4, 1]          # stay nights per booking

print(f"PR-AUC: {average_precision_score(y_true, y_pred)}")
print(f"Business Impact: {business_impact_score(y_true, y_pred, adr, stay_nights)}")

PR-AUC: 0.5
Business Impact: -240

In [29]:
# Main function

def benchmark_models(models: dict, pipeline: Pipeline|ImbPipeline, 
                     X, y, cv=5, scoring_metrics=None, return_raw=False):
    """
    Run cross-validated benchmarking across multiple models.

    Parameters:
    - models: dict of {model_name: model_object}
    - X: Features
    - y: Target labels
    - cv: Cross-validation folds (int or CV splitter)
    - scoring_metrics: dict of scorers (default: PR-AUC and Business Impact)
    - return_raw: if True, returns full raw result dictionary

    Returns:
    - DataFrame with mean and std of each metric per model
    """
    if scoring_metrics is None:
        scoring_metrics = {
            "pr_auc": "average_precision",
            "business_impact": business_scorer}

    results = []

    for name, model in models.items():
        print(f"Evaluating {name}...    ", end="")
        clf = clone(pipeline) # ensure independence
        clf.set_params(classifier=model)
        cv_result = cross_validate(
            clf,
            X, y,
            cv=cv,
            scoring=scoring_metrics,
            return_train_score=True,
            n_jobs=-1
        )

        result_summary = {
            "Model": name
        }

        for metric_key in scoring_metrics:
            train_scores = cv_result[f'train_{metric_key}']
            result_summary[f"Train {metric_key.upper()} Mean"] = np.mean(train_scores)
            result_summary[f"Train {metric_key.upper()} Std"] = np.std(train_scores)

            test_scores = cv_result[f'test_{metric_key}']
            result_summary[f"Test {metric_key.upper()} Mean"] = np.mean(test_scores)
            result_summary[f"Test {metric_key.upper()} Std"] = np.std(test_scores)

            result_summary["Fit Time Mean"] = np.mean(cv_result["fit_time"])
            result_summary["Score Time Mean"] = np.mean(cv_result["score_time"])

        if return_raw:
            result_summary["Raw"] = cv_result

        results.append(result_summary)

        print("Done!")

    return pd.DataFrame(results).sort_values(by="Test PR_AUC Mean", ascending=False)

# 7.2 Pipeline Setup

In [30]:
# Baseline Pipeline
baseline_pipeline = ImbPipeline([
    ("feature_generator", feature_generator),
    ("preprocessor", baseline_preprocessor),
    ("classifier", models["Baseline Model"])
])

baseline_pipeline

Pipeline(steps=[('feature_generator',
                 MultiColumnCombiner(combinations={'total_guests': ['adults',
                                                                    'children',
                                                                    'babies'],
                                                   'total_stay_nights': ['stays_in_weekend_nights',
                                                                         'stays_in_week_nights']})),
                ('preprocessor',
                 ColumnTransformer(transformers=[('num_pipeline',
                                                  Pipeline(steps=[('clipper',
                                                                   OutlierClipper(columns=['adr'],
                                                                                  whisker=3.0)),
                                                                  ('scaler',
                                                                   ADRScaler())]...
                                                                                 handle_unknown='ignore'))]),
                                                  ['hotel', 'meal',
                                                   'market_segment',
                                                   'distribution_channel',
                                                   'reserved_room_type',
                                                   'assigned_room_type',
                                                   'deposit_type',
                                                   'customer_type']),
                                                 ('binary_pipeline',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   BinaryEncoder())]),
                                                  ['country'])],
                                   verbose_feature_names_out=False)),
                ('classifier', DummyClassifier())])

In [31]:
# Advance Pipeline

# Baseline Pipeline + Resample
baseline_pipeline_resample = ImbPipeline([
    ("feature_generator", feature_generator),
    ("preprocessor", baseline_preprocessor),
    ("resample", SMOTE(random_state=42)),
    ("classifier", models["Baseline Model"])
])

baseline_pipeline_resample

Pipeline(steps=[('feature_generator',
                 MultiColumnCombiner(combinations={'total_guests': ['adults',
                                                                    'children',
                                                                    'babies'],
                                                   'total_stay_nights': ['stays_in_weekend_nights',
                                                                         'stays_in_week_nights']})),
                ('preprocessor',
                 ColumnTransformer(transformers=[('num_pipeline',
                                                  Pipeline(steps=[('clipper',
                                                                   OutlierClipper(columns=['adr'],
                                                                                  whisker=3.0)),
                                                                  ('scaler',
                                                                   ADRScaler())]...
                                                   'market_segment',
                                                   'distribution_channel',
                                                   'reserved_room_type',
                                                   'assigned_room_type',
                                                   'deposit_type',
                                                   'customer_type']),
                                                 ('binary_pipeline',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   BinaryEncoder())]),
                                                  ['country'])],
                                   verbose_feature_names_out=False)),
                ('resample', SMOTE(random_state=42)),
                ('classifier', DummyClassifier())])

In [32]:
# Pipeline Testing

cv_result = cross_validate(
    baseline_pipeline,
    x_train, y_train,
    cv=5,
    scoring={"pr_auc": "average_precision",
             "business_impact": business_scorer},
    return_train_score=True
)
cv_result

{'fit_time': array([0.13852215, 0.14069223, 0.14410496, 0.13715839, 0.13031983]),
 'score_time': array([0.05655432, 0.05617929, 0.05651641, 0.04992485, 0.05055928]),
 'test_pr_auc': array([0.27523511, 0.27523511, 0.27523511, 0.27523511, 0.27523511]),
 'train_pr_auc': array([0.27523511, 0.27523511, 0.27523511, 0.27523511, 0.27523511]),
 'test_business_impact': array([nan, nan, nan, nan, nan]),
 'train_business_impact': array([nan, nan, nan, nan, nan])}

## 7.3 Model Benchmarking
Select best model based on cross-validation result

In [33]:
# Model benchmarking using Stratified K-Fold
sf = StratifiedKFold(n_splits=5)

### Experiment 1. Select Best Preprocessor

In [34]:
# 1.1 Baseline Preprocessing
bcmk_baseline = benchmark_models(models, baseline_pipeline, 
                                 x_train, y_train, cv=sf)

Evaluating Baseline Model...    Done!
Evaluating K-Nearest Neighbors...    Done!
Evaluating Decision Tree Classifier...    Done!
Evaluating Logistic Regression...    Done!
Evaluating Random Forest Classifiers...    Done!
Evaluating Adaboost Classifier...    Done!
Evaluating XGBoost Classifier...    Done!

In [35]:
bcmk_baseline

,Model,Train PR_AUC Mean,Train PR_AUC Std,Test PR_AUC Mean,Test PR_AUC Std,Fit Time Mean,Score Time Mean,Train BUSINESS_IMPACT Mean,Train BUSINESS_IMPACT Std,Test BUSINESS_IMPACT Mean,Test BUSINESS_IMPACT Std
6,XGBoost Classifier,0.835574,0.001395,0.759079,0.008610,0.891071,0.108839,NaN,NaN,NaN,NaN
4,Random Forest Classifiers,0.999957,0.000006,0.743250,0.008759,4.273909,0.416412,NaN,NaN,NaN,NaN
5,Adaboost Classifier,0.620885,0.006315,0.620426,0.011197,2.767002,0.267565,NaN,NaN,NaN,NaN
3,Logistic Regression,0.616292,0.005070,0.614565,0.007137,0.652952,0.065000,NaN,NaN,NaN,NaN
2,Decision Tree Classifier,0.999968,0.000004,0.438352,0.007516,0.440110,0.069208,NaN,NaN,NaN,NaN
1,K-Nearest Neighbors,0.661503,0.001505,0.418214,0.005112,0.176193,4.182901,NaN,NaN,NaN,NaN
0,Baseline Model,0.275235,0.000000,0.275235,0.000000,0.170040,0.065659,NaN,NaN,NaN,NaN

Top 3 Model
1. Decition Tree Classifier
2. Random Forest Calssifier
3. XBboost Classifier

Train with 
- 1.2 Baseline with Rare Label Handing

In [36]:
top_model = ["Random Forest Classifiers", "XGBoost Classifier", "Decision Tree Classifier"]

model_candidate = models.copy()
model_candidate = {k: model_candidate[k] for k in model_candidate if k in top_model}

In [37]:
# 1.3 Baseline Preprocessing with Rare Label handling

baseline_rare = clone(baseline_pipeline)
baseline_rare.set_params(preprocessor = rare_preprocessor)

bmck_baseline_rare = benchmark_models(model_candidate, baseline_rare, 
                                      x_train, y_train, cv=sf)

Evaluating Decision Tree Classifier...    Done!
Evaluating Random Forest Classifiers...    Done!
Evaluating XGBoost Classifier...    Done!

In [38]:
bmck_baseline_rare

,Model,Train PR_AUC Mean,Train PR_AUC Std,Test PR_AUC Mean,Test PR_AUC Std,Fit Time Mean,Score Time Mean,Train BUSINESS_IMPACT Mean,Train BUSINESS_IMPACT Std,Test BUSINESS_IMPACT Mean,Test BUSINESS_IMPACT Std
2,XGBoost Classifier,0.834205,0.001925,0.755930,0.006482,0.717562,0.119060,NaN,NaN,NaN,NaN
1,Random Forest Classifiers,0.999953,0.000006,0.741813,0.008720,4.000821,0.401529,NaN,NaN,NaN,NaN
0,Decision Tree Classifier,0.999967,0.000004,0.442860,0.007498,0.431888,0.095885,NaN,NaN,NaN,NaN

In [39]:
all_experiment = [
    bcmk_baseline.head(3),
    bmck_baseline_rare.head(3),
]


summary = pd.concat(all_experiment).sort_values("Test PR_AUC Mean", ascending=False)
summary.head(3)

,Model,Train PR_AUC Mean,Train PR_AUC Std,Test PR_AUC Mean,Test PR_AUC Std,Fit Time Mean,Score Time Mean,Train BUSINESS_IMPACT Mean,Train BUSINESS_IMPACT Std,Test BUSINESS_IMPACT Mean,Test BUSINESS_IMPACT Std
6,XGBoost Classifier,0.835574,0.001395,0.759079,0.008610,0.891071,0.108839,NaN,NaN,NaN,NaN
2,XGBoost Classifier,0.834205,0.001925,0.755930,0.006482,0.717562,0.119060,NaN,NaN,NaN,NaN
4,Random Forest Classifiers,0.999957,0.000006,0.743250,0.008759,4.273909,0.416412,NaN,NaN,NaN,NaN

Best Model
1. XGBoost Classifier
2. RandomForest

### Experiment 2. Try with Resampling

In [40]:
#### Model 1. XGBoost

Before Resampling (Evaluate on Data Testing)

In [41]:
# Model 1: XGBoost Baseline Classifier

xgb_baseline = clone(baseline_pipeline)
xgb_baseline.set_params(preprocessor = baseline_preprocessor,
                        classifier = models["XGBoost Classifier"])
xgb_baseline.fit(x_train, y_train)

Pipeline(steps=[('feature_generator',
                 MultiColumnCombiner(combinations={'total_guests': ['adults',
                                                                    'children',
                                                                    'babies'],
                                                   'total_stay_nights': ['stays_in_weekend_nights',
                                                                         'stays_in_week_nights']})),
                ('preprocessor',
                 ColumnTransformer(transformers=[('num_pipeline',
                                                  Pipeline(steps=[('clipper',
                                                                   OutlierClipper(columns=['adr'],
                                                                                  whisker=3.0)),
                                                                  ('scaler',
                                                                   ADRScaler())]...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=None, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [42]:
# Predict and Score
pred_train = xgb_baseline.predict(x_train)
pred_test = xgb_baseline.predict(x_test)

# PR-AUC Score
print("Train PR-AUC: ", average_precision_score(y_train, pred_train))
print("Test PR-AUC: ", average_precision_score(y_test, pred_test))

# Classification Report
print("Classification Report (Train): ")
print(classification_report(y_train, pred_train))
print("Classification Report (Test): ")
print(classification_report(y_test, pred_test))

Train PR-AUC:  0.6068798158821511
Test PR-AUC:  0.5627564989577869
Classification Report (Train):
              precision    recall  f1-score   support

           0       0.88      0.93      0.90     40460
           1       0.78      0.66      0.71     15365

    accuracy                           0.85     55825
   macro avg       0.83      0.79      0.81     55825
weighted avg       0.85      0.85      0.85     55825

Classification Report (Test):
              precision    recall  f1-score   support

           0       0.86      0.92      0.89     10116
           1       0.74      0.62      0.67      3841

    accuracy                           0.84     13957
   macro avg       0.80      0.77      0.78     13957
weighted avg       0.83      0.84      0.83     13957

After Resampling (Evaluate on Data Testing)

In [43]:
resampler = {
    "SMOTE": SMOTE(random_state=42),
    "Random Oversampling": RandomOverSampler(random_state=42),
    "Random Undersampling": RandomUnderSampler(random_state=42),
    "Near Miss": NearMiss()
}

In [44]:
# Model 1: XGBoost Baseline Classifier
# Experiment 2. Try different resampling

xgb_baseline = clone(baseline_pipeline_resample)
xgb_baseline.set_params(preprocessor = baseline_preprocessor,
                        classifier = XGBClassifier(random_state=42))

Pipeline(steps=[('feature_generator',
                 MultiColumnCombiner(combinations={'total_guests': ['adults',
                                                                    'children',
                                                                    'babies'],
                                                   'total_stay_nights': ['stays_in_weekend_nights',
                                                                         'stays_in_week_nights']})),
                ('preprocessor',
                 ColumnTransformer(transformers=[('num_pipeline',
                                                  Pipeline(steps=[('clipper',
                                                                   OutlierClipper(columns=['adr'],
                                                                                  whisker=3.0)),
                                                                  ('scaler',
                                                                   ADRScaler())]...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=None, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [46]:
search_resampler_xgboost = GridSearchCV(
    estimator=xgb_baseline,
    param_grid={"resample": list(resampler.values())},
    scoring="average_precision",
    cv=sf,
    return_train_score=True,
    verbose = 1
)

search_resampler_xgboost.fit(x_train, y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=Pipeline(steps=[('feature_generator',
                                        MultiColumnCombiner(combinations={'total_guests': ['adults',
                                                                                           'children',
                                                                                           'babies'],
                                                                          'total_stay_nights': ['stays_in_weekend_nights',
                                                                                                'stays_in_week_nights']})),
                                       ('preprocessor',
                                        ColumnTransformer(transformers=[('num_pipeline',
                                                                         Pipeline(...
                                                      max_leaves=None,
                                                      min_child_weight=None,
                                                      missing=nan,
                                                      monotone_constraints=None,
                                                      multi_strategy=None,
                                                      n_estimators=None,
                                                      n_jobs=None,
                                                      num_parallel_tree=None, ...))]),
             param_grid={'resample': [SMOTE(random_state=42),
                                      RandomOverSampler(random_state=42),
                                      RandomUnderSampler(random_state=42),
                                      NearMiss()]},
             return_train_score=True, scoring='average_precision', verbose=1)

In [47]:
search_resampler_xgboost.best_params_

{'resample': SMOTE(random_state=42)}

In [48]:
pd.DataFrame(search_resampler_xgboost.cv_results_).sort_values("mean_test_score", ascending=False).head(4)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_resample,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score,split0_train_score,split1_train_score,split2_train_score,split3_train_score,split4_train_score,mean_train_score,std_train_score
0,1.178407,1.192790,0.041248,0.001978,SMOTE(random_state=42),{'resample': SMOTE(random_state=42)},0.755880,0.759897,0.770037,0.748112,0.748807,0.756547,0.008059,1,0.820565,0.821321,0.820772,0.820178,0.819511,0.820470,0.000605
1,0.340659,0.012270,0.042577,0.002259,RandomOverSampler(random_state=42),{'resample': RandomOverSampler(random_state=42)},0.756533,0.757670,0.769170,0.747864,0.740949,0.754437,0.009561,2,0.829654,0.828425,0.827189,0.825694,0.826593,0.827511,0.001391
2,0.281853,0.032574,0.043271,0.002035,RandomUnderSampler(random_state=42),{'resample': RandomUnderSampler(random_state=42)},0.746012,0.752619,0.761826,0.740611,0.739014,0.748016,0.008388,3,0.811551,0.812807,0.808502,0.811430,0.810904,0.811039,0.001414
3,0.533116,0.020763,0.043391,0.001239,NearMiss(),{'resample': NearMiss()},0.547997,0.543083,0.552277,0.552401,0.535079,0.546167,0.006511,4,0.564253,0.573303,0.565571,0.574420,0.562208,0.567951,0.004956

In [49]:
# Predict and Score
pred_train_resample = search_resampler_xgboost.best_estimator_.predict(x_train)
pred_test_resample = search_resampler_xgboost.best_estimator_.predict(x_test)

# PR-AUC Score
print("Train PR-AUC: ", average_precision_score(y_train, pred_train_resample))
print("Test PR-AUC: ", average_precision_score(y_test, pred_test_resample))

# Classification Report
print("Classification Report (Train): ")
print(classification_report(y_train, pred_train_resample))
print("Classification Report (Test): ")
print(classification_report(y_test, pred_test_resample))

Train PR-AUC:  0.5988555508237043
Test PR-AUC:  0.5567104883061068
Classification Report (Train):
              precision    recall  f1-score   support

           0       0.88      0.92      0.90     40460
           1       0.76      0.67      0.71     15365

    accuracy                           0.85     55825
   macro avg       0.82      0.79      0.81     55825
weighted avg       0.85      0.85      0.85     55825

Classification Report (Test):
              precision    recall  f1-score   support

           0       0.87      0.91      0.89     10116
           1       0.72      0.63      0.67      3841

    accuracy                           0.83     13957
   macro avg       0.79      0.77      0.78     13957
weighted avg       0.83      0.83      0.83     13957

In [50]:
print("Summary XGB Baseline Classifier")
print("\nBefore Tunning:")
print("Train PR-AUC: ", average_precision_score(y_train, pred_train))
print("Test PR-AUC: ", average_precision_score(y_test, pred_test))

print("\nAfter Tunning:")
print("Train PR-AUC: ", average_precision_score(y_train, pred_train_resample))
print("Test PR-AUC: ", average_precision_score(y_test, pred_test_resample))

Summary XGB Baseline Classifier

Before Tunning:
Train PR-AUC:  0.6068798158821511
Test PR-AUC:  0.5627564989577869

After Tunning:
Train PR-AUC:  0.5988555508237043
Test PR-AUC:  0.5567104883061068

#### Model 2. Random Forest

Before Resampling

In [51]:
# Model 2: Random Forest Baseline Classifier

rf_baseline = clone(baseline_pipeline)
rf_baseline.set_params(preprocessor = baseline_preprocessor,
                        classifier = models["Random Forest Classifiers"])
rf_baseline.fit(x_train, y_train)

Pipeline(steps=[('feature_generator',
                 MultiColumnCombiner(combinations={'total_guests': ['adults',
                                                                    'children',
                                                                    'babies'],
                                                   'total_stay_nights': ['stays_in_weekend_nights',
                                                                         'stays_in_week_nights']})),
                ('preprocessor',
                 ColumnTransformer(transformers=[('num_pipeline',
                                                  Pipeline(steps=[('clipper',
                                                                   OutlierClipper(columns=['adr'],
                                                                                  whisker=3.0)),
                                                                  ('scaler',
                                                                   ADRScaler())]...
                                                  ['hotel', 'meal',
                                                   'market_segment',
                                                   'distribution_channel',
                                                   'reserved_room_type',
                                                   'assigned_room_type',
                                                   'deposit_type',
                                                   'customer_type']),
                                                 ('binary_pipeline',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   BinaryEncoder())]),
                                                  ['country'])],
                                   verbose_feature_names_out=False)),
                ('classifier', RandomForestClassifier(random_state=42))])

In [52]:
# Predict and Score
pred_train = rf_baseline.predict(x_train)
pred_test = rf_baseline.predict(x_test)

# PR-AUC Score
print("Train PR-AUC: ", average_precision_score(y_train, pred_train))
print("Test PR-AUC: ", average_precision_score(y_test, pred_test))

# Classification Report
print("Classification Report (Train): ")
print(classification_report(y_train, pred_train))
print("Classification Report (Test): ")
print(classification_report(y_test, pred_test))

Train PR-AUC:  0.9940785197024822
Test PR-AUC:  0.5452464892362521
Classification Report (Train):
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     40460
           1       1.00      1.00      1.00     15365

    accuracy                           1.00     55825
   macro avg       1.00      1.00      1.00     55825
weighted avg       1.00      1.00      1.00     55825

Classification Report (Test):
              precision    recall  f1-score   support

           0       0.85      0.92      0.89     10116
           1       0.73      0.59      0.65      3841

    accuracy                           0.83     13957
   macro avg       0.79      0.75      0.77     13957
weighted avg       0.82      0.83      0.82     13957

After Resampling

In [53]:
# Model 2: Random Forest Baseline Classifier + Grouping Transaction

rf_baseline_resample = clone(baseline_pipeline_resample)
rf_baseline_resample.set_params(preprocessor = baseline_preprocessor,
                        classifier = models["Random Forest Classifiers"])

Pipeline(steps=[('feature_generator',
                 MultiColumnCombiner(combinations={'total_guests': ['adults',
                                                                    'children',
                                                                    'babies'],
                                                   'total_stay_nights': ['stays_in_weekend_nights',
                                                                         'stays_in_week_nights']})),
                ('preprocessor',
                 ColumnTransformer(transformers=[('num_pipeline',
                                                  Pipeline(steps=[('clipper',
                                                                   OutlierClipper(columns=['adr'],
                                                                                  whisker=3.0)),
                                                                  ('scaler',
                                                                   ADRScaler())]...
                                                   'distribution_channel',
                                                   'reserved_room_type',
                                                   'assigned_room_type',
                                                   'deposit_type',
                                                   'customer_type']),
                                                 ('binary_pipeline',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   BinaryEncoder())]),
                                                  ['country'])],
                                   verbose_feature_names_out=False)),
                ('resample', SMOTE(random_state=42)),
                ('classifier', RandomForestClassifier(random_state=42))])

In [55]:
search_resampler_rf = GridSearchCV(
    estimator=rf_baseline_resample,
    param_grid={"resample": list(resampler.values())},
    scoring="average_precision",
    cv=sf,
    return_train_score=True
)

search_resampler_rf.fit(x_train, y_train)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=Pipeline(steps=[('feature_generator',
                                        MultiColumnCombiner(combinations={'total_guests': ['adults',
                                                                                           'children',
                                                                                           'babies'],
                                                                          'total_stay_nights': ['stays_in_weekend_nights',
                                                                                                'stays_in_week_nights']})),
                                       ('preprocessor',
                                        ColumnTransformer(transformers=[('num_pipeline',
                                                                         Pipeline(...
                                                                                         ('encoder',
                                                                                          BinaryEncoder())]),
                                                                         ['country'])],
                                                          verbose_feature_names_out=False)),
                                       ('resample', SMOTE(random_state=42)),
                                       ('classifier',
                                        RandomForestClassifier(random_state=42))]),
             param_grid={'resample': [SMOTE(random_state=42),
                                      RandomOverSampler(random_state=42),
                                      RandomUnderSampler(random_state=42),
                                      NearMiss()]},
             return_train_score=True, scoring='average_precision')

In [56]:
search_resampler_rf.best_params_

{'resample': SMOTE(random_state=42)}

In [57]:
search_resampler_rf.best_score_

np.float64(0.736550955950498)

In [58]:
pd.DataFrame(search_resampler_rf.cv_results_).sort_values("mean_test_score", ascending=False).head(4)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_resample,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score,split0_train_score,split1_train_score,split2_train_score,split3_train_score,split4_train_score,mean_train_score,std_train_score
0,5.822399,0.051628,0.180069,0.005273,SMOTE(random_state=42),{'resample': SMOTE(random_state=42)},0.732174,0.734559,0.752813,0.734780,0.728429,0.736551,0.008446,1,0.999871,0.999952,0.999897,0.999902,0.999878,0.999900,0.000028
1,4.757419,0.156391,0.186505,0.008108,RandomOverSampler(random_state=42),{'resample': RandomOverSampler(random_state=42)},0.728325,0.732678,0.752011,0.729183,0.720786,0.732597,0.010453,2,0.999781,0.999815,0.999793,0.999820,0.999823,0.999806,0.000016
2,1.858338,0.041734,0.152903,0.004097,RandomUnderSampler(random_state=42),{'resample': RandomUnderSampler(random_state=42)},0.721097,0.732412,0.741355,0.724398,0.719160,0.727684,0.008199,3,0.953975,0.954246,0.950916,0.952746,0.955210,0.953419,0.001478
3,2.150309,0.031985,0.150762,0.004689,NearMiss(),{'resample': NearMiss()},0.599242,0.597363,0.606114,0.603925,0.605653,0.602459,0.003522,4,0.819416,0.821817,0.816717,0.822484,0.826904,0.821467,0.003391

In [59]:
# Predict and Score
pred_train_resample = search_resampler_rf.best_estimator_.predict(x_train)
pred_test_resample = search_resampler_rf.best_estimator_.predict(x_test)

# PR-AUC Score
print("Train PR-AUC: ", average_precision_score(y_train, pred_train_resample))
print("Test PR-AUC: ", average_precision_score(y_test, pred_test_resample))

# Classification Report
print("Classification Report (Train): ")
print(classification_report(y_train, pred_train_resample))
print("Classification Report (Test): ")
print(classification_report(y_test, pred_test_resample))

Train PR-AUC:  0.9941432341759758
Test PR-AUC:  0.5503095950571056
Classification Report (Train):
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     40460
           1       1.00      1.00      1.00     15365

    accuracy                           1.00     55825
   macro avg       1.00      1.00      1.00     55825
weighted avg       1.00      1.00      1.00     55825

Classification Report (Test):
              precision    recall  f1-score   support

           0       0.86      0.91      0.89     10116
           1       0.73      0.61      0.66      3841

    accuracy                           0.83     13957
   macro avg       0.79      0.76      0.77     13957
weighted avg       0.82      0.83      0.82     13957